import Head from 'next/head'
import { BiWorld } from 'react-icons/bi'
import Main from '../components/Main'
import Events from "../components/prayer"
import Services from '../components/services'


export default function Home() {
  return (
    <>
      <Head>
        <title>Mosque </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <Events />
      <Services />
    </>
  )
}
